export const initialOrderDetails = {
  branch: {
    value: "",
    error: false,
    text: "Branch",
    placeholder: "Select Branch",
    helperText: "Please select the option",
    type: "select",
    options: [
      { name: "AA", value: "AA" },
      { name: "AB", value: "AB" },
      { name: "AC", value: "AC" },
      { name: "AD", value: "AD" },
    ],
  },
  remeasure: {
    value: "Yes",
    error: false,
    text: "Remeasure Required?",
    placeholder: "Yes",
    helperText: "Please select the option",
    type: "select",
    options: [
      { name: "Yes", value: "Yes" },
      { name: "No", value: "No" },
    ],
  },
  orderType: {
    value: "Supply & Install",
    error: false,
    text: "Order Type",
    placeholder: "Supply & Install",
    helperText: "Please select the option",
    type: "select",
    options: [
      { name: "Supply & Install", value: "Supply & Install" },
      { name: "Supply Only", value: "Supply Only" },
    ],
  },
  deliveryZone: {
    value: "",
    error: false,
    text: "Delivery Zone",
    placeholder: "Select Delivery Zone",
    helperText: "Please select the option",
    type: "select",
    options: [
      { name: "Zone1", value: "Zone1" },
      { name: "Zone2", value: "Zone2" },
    ],
  },
  homeDepot: {
    value: "",
    error: false,
    text: "Home Depot Order",
    placeholder: "Select Option",
    helperText: "Please select the option",
    type: "select",
    options: [
      { name: "H1", value: "H1" },
      { name: "H2", value: "H2" },
    ],
  },
  paymentType: {
    value: "",
    error: false,
    text: "Payment Type",
    placeholder: "Select Payment Type",
    helperText: "Please select the option",
    type: "select",
    options: [
      { name: "Cash", value: "Cash" },
      { name: "Card", value: "Card" },
    ],
  },
  leadSource: {
    value: "",
    error: false,
    text: "Lead Source",
    placeholder: "Lead Name",
    helperText: "Field should not be null",
    type: "textbox",
  },
  sellPrice: {
    value: "",
    error: false,
    text: "Sell Price (Before Tax)",
    placeholder: "0",
    helperText: "Field should not be null",
    type: "textbox",
  },
  estimator: {
    value: "",
    error: false,
    text: "Estimator",
    placeholder: "Select Estimator",
    helperText: "Please select the option",
    type: "select",
    options: [
      { name: "E1", value: "E1" },
      { name: "E2", value: "E2" },
    ],
  },

  listPrice: {
    value: "",
    error: false,
    text: "List Price",
    placeholder: "0.00",
    helperText: "Field should not be null",
    type: "textbox",
  },
  marketer: {
    value: "",
    error: false,
    text: "Marketer",
    placeholder: "Marketer Name",
    helperText: "Field should not be null",
    type: "textbox",
  },
  depositValue: {
    value: "",
    error: false,
    text: "Deposit Value",
    placeholder: "0",
    helperText: "Field should not be null",
    type: "textbox",
  },
  discount: {
    value: "",
    error: false,
    text: "Discount %",
    placeholder: "0",
    helperText: "Field should not be null",
    type: "textbox",
  },
  commission: {
    value: "",
    error: false,
    text: "Commission %",
    placeholder: "0",
    helperText: "Field should not be null",
    type: "textbox",
  },
};

export const initialSummaryInfo = {
  windows: {
    value: "",
    error: false,
    text: "Windows",
    placeholder: "0",
    type: "textbox",
    helperText: "Field should not be null",
  },
  patioDoors: {
    value: "",
    error: false,
    helperText: "Field should not be null",
    text: "Patio Doors",
    type: "textbox",
    placeholder: "0",
  },
  doors: {
    value: "",
    error: false,
    text: "Doors",
    type: "textbox",
    placeholder: "0",
    helperText: "Field should not be null",
  },
  sealedUnits: {
    value: "",
    error: false,
    text: "Sealed Units",
    type: "textbox",
    placeholder: "0",
    helperText: "Field should not be null",
  },
  others: {
    value: "",
    error: false,
    text: "Others",
    type: "textbox",
    placeholder: "0",
    helperText: "Field should not be null",
  },
  submitterEmail: {
    value: "",
    error: false,
    text: "Submitter Email",
    type: "textbox",
    placeholder: "JohnDone@gmail.com",
    helperText: "please enter valid Submitter Email",
    inputProps: {
      type: "email",
    },
  },
  iqpCode: {
    value: "",
    error: false,
    text: "CleanBC IQP Code Required Before Ordering Product?",
    type: "select",
    placeholder: "Select Option",
    helperText: "Please select the option",
    options: [
      { name: "Yes", value: "Yes" },
      { name: "N/A", value: "N/A" },
    ],
  },
  codelProgram: {
    value: "N/A",
    error: false,
    text: "Doors Saved in Codel Program?",
    type: "select",
    placeholder: "N/A",
    helperText: "Please select the option",
    options: [
      { name: "Yes", value: "Yes" },
      { name: "N/A", value: "N/A" },
    ],
  },
  futureOpp: {
    value: "",
    error: false,
    text: "Was a Future Opportunity Created?",
    type: "select",
    placeholder: "Select Option",
    helperText: "Please select the option",
    options: [
      { name: "Yes", value: "Yes" },
      { name: "N/A", value: "N/A" },
    ],
  },
  drawingPrice: {
    value: "",
    error: false,
    text: "Alteration Drawing & Price Breakdown Submitted?",
    type: "select",
    placeholder: "Select Option",
    helperText: "Please select the option",
    options: [
      { name: "Yes", value: "Yes" },
      { name: "N/A", value: "N/A" },
    ],
  },
};
export const initialCustomerInfo = {
  custNumber: {
    value: "",
    key: "custNumber",
    error: false,
    text: "Customer Number",
    placeholder: "123456",
    helperText: "please enter customer Number",
  },
  address: {
    value: "",
    error: false,
    text: "Street Address",
    placeholder: "Search Address",
    helperText: "please enter Street Address",
  },
  workOrder: {
    value: "",
    error: false,
    text: "Work Orde#",
    placeholder: "A12400",
    helperText: "please enter Work orde#",
  },
  province: {
    value: "",
    error: false,
    text: "Province",
    placeholder: "BC",
    helperText: "please enter Province",
  },
  custName: {
    value: "",
    error: false,
    text: "Customer Name",
    placeholder: "John Doe",
    helperText: "please enter customer Name",
  },
  city: {
    value: "",
    error: false,
    text: "City",
    placeholder: "Langley",
    helperText: "please enter City",
  },

  email: {
    value: "",
    error: false,
    text: "Email",
    helperText: "please enter valid Email",
    placeholder: "JohnDoe@gmail.com",
    inputProps: {
      type: "email",
    },
  },
  postalCode: {
    value: "",
    error: false,
    text: "Postal Code",
    placeholder: "V3E2X5",
    helperText: "please enter valid Postal Code",
    inputProps:{
      pattern: "^[A-Za-z]\\d[A-Za-z]\\d[A-Za-z]\\d$",
    }
  },
  phoneNumber: {
    value: "",
    error: false,
    text: "Phone Number",
    placeholder: "604-123-1234",
    helperText: "please enter valid Phone Number",
    inputProps:{
      pattern: "[0-9]{10}",
    }
  },
};
